import type { TestSimScenario } from '../types'

export const guangzhou614Scenario: TestSimScenario = {
  id: 'ts-guangzhou-614',
  code: 'guangzhou_614',
  caseId: '40000000-0000-0000-0000-000000000005',
  title: '广州智光储能科技「6·14」锂电池包闪爆事故推演',
  subtitle: '储能测试作业安全 · 数字孪生 · 分支决策 · AI安全导师',
  location: '广州黄埔区',
  accidentDate: '2024-06-14',
  projectName: '锂电池包性能测试',
  testPurpose: '充放电循环与容量标定',
  testObject: '1# 锂电池包（磷酸铁锂模组）',
  testEnv: '室内测试区，环境温度 32℃，通风一般',
  personnel: '测试工程师 2 人、现场监护 1 人',
  durationMinutes: 45,
  nodes: [
    {
      key: 'n0', phase: 'background', clock: '14:00', offsetMin: 0, title: '事故背景',
      narrative: '测试区完成上电检查，1# 电池包进入充放电循环测试。BMS、消防、气体监测均在线。',
      telemetry: { clock: '14:00', envTemp: 32, packTemp: 28, voltage: 51.2, current: 12, soc: 65, soh: 98, insulation: '正常', gasPpm: 0, vocPpm: 0, pressure: 101, alarmCount: 0 },
      scene: { packHeat: 0.1, packColor: 'normal', smoke: 0, flash: 0, ventOn: true, personnelEvacuated: false },
    },
    {
      key: 'n1', phase: 'testing', clock: '14:10', offsetMin: 10, title: '测试作业',
      narrative: '测试正式开始，电压、电流、温度曲线平稳，BMS 状态正常。风险处于低位。',
      telemetry: { clock: '14:10', envTemp: 32, packTemp: 32, voltage: 51.0, current: 25, soc: 68, soh: 98, insulation: '正常', gasPpm: 5, vocPpm: 2, pressure: 101, alarmCount: 0 },
      scene: { packHeat: 0.15, packColor: 'normal', smoke: 0, flash: 0, ventOn: true, personnelEvacuated: false },
    },
    {
      key: 'n2', phase: 'anomaly', clock: '14:24', offsetMin: 24, title: '异常征兆',
      narrative: 'BMS 一级告警：1# 电池包温度 65℃，电压离散度增大，电流波动。异常电池在孪生场景中变黄。',
      telemetry: { clock: '14:24', envTemp: 33, packTemp: 65, voltage: 49.8, current: 38, soc: 71, soh: 97, insulation: '下降', gasPpm: 45, vocPpm: 28, pressure: 102, alarmCount: 1 },
      scene: { packHeat: 0.45, packColor: 'warning', smoke: 0.08, flash: 0, ventOn: true, personnelEvacuated: false },
    },
    {
      key: 'n3', phase: 'thermal_runaway', clock: '14:28', offsetMin: 28, title: '热失控发展',
      narrative: '温度 65→120→180℃ 快速攀升，可燃气体浓度陡增。热成像显示异常区域由黄转橙再转红。',
      telemetry: { clock: '14:28', envTemp: 38, packTemp: 180, voltage: 42.1, current: 0, soc: 70, soh: 0, insulation: '失效', gasPpm: 1200, vocPpm: 850, pressure: 108, alarmCount: 5 },
      scene: { packHeat: 0.85, packColor: 'danger', smoke: 0.55, flash: 0, ventOn: false, personnelEvacuated: false },
    },
    {
      key: 'n4', phase: 'flashover', clock: '14:30', offsetMin: 30, title: '闪爆发生',
      narrative: '可燃气体达到爆炸下限，电池包发生闪爆。火光、烟雾、冲击波波及测试区，设备损毁。',
      telemetry: { clock: '14:30', envTemp: 55, packTemp: 420, voltage: 0, current: 0, soc: 0, soh: 0, insulation: '失效', gasPpm: 0, vocPpm: 0, pressure: 145, alarmCount: 12 },
      scene: { packHeat: 1, packColor: 'critical', smoke: 1, flash: 1, ventOn: false, personnelEvacuated: false },
    },
    {
      key: 'n5', phase: 'emergency', clock: '14:35', offsetMin: 35, title: '应急处置',
      narrative: '应急队伍到场，封锁现场、搜救伤员、气体监测与通风处置同步展开。',
      telemetry: { clock: '14:35', envTemp: 42, packTemp: 85, voltage: 0, current: 0, soc: 0, soh: 0, insulation: '失效', gasPpm: 320, vocPpm: 180, pressure: 103, alarmCount: 3 },
      scene: { packHeat: 0.5, packColor: 'danger', smoke: 0.6, flash: 0, ventOn: true, personnelEvacuated: true },
    },
    {
      key: 'n6', phase: 'investigation', clock: '14:42', offsetMin: 40, title: '事故调查',
      narrative: '证据链汇聚：监控、BMS 日志、温感、气体记录与操作票证交叉印证，启动 FTA 与 5Why 分析。',
      telemetry: { clock: '14:42', envTemp: 30, packTemp: 35, voltage: 0, current: 0, soc: 0, soh: 0, insulation: '—', gasPpm: 0, vocPpm: 0, pressure: 101, alarmCount: 0 },
      scene: { packHeat: 0.2, packColor: 'normal', smoke: 0.1, flash: 0, ventOn: true, personnelEvacuated: true },
    },
    {
      key: 'n7', phase: 'debrief', clock: '—', offsetMin: 45, title: 'AI复盘',
      narrative: '推演结束，生成《事故学习报告》与能力画像。',
      telemetry: { clock: '—', envTemp: 30, packTemp: 30, voltage: 0, current: 0, soc: 0, soh: 0, insulation: '—', gasPpm: 0, vocPpm: 0, pressure: 101, alarmCount: 0 },
      scene: { packHeat: 0.1, packColor: 'normal', smoke: 0, flash: 0, ventOn: true, personnelEvacuated: true },
    },
  ],
  decisions: [
    {
      id: 'd1', phase: 'background', nodeKey: 'n0',
      title: '决策点① · 测试前安全确认',
      question: '开始测试前应重点确认哪些内容？',
      regulationRef: '《储能系统测试安全规范》',
      timeLimitSec: 90,
      options: [
        { id: 'a', label: '测试设备状态', riskDelta: 15, isOptimal: false, consequence: '遗漏电池与消防确认', branch: 'continue' },
        { id: 'b', label: '电池包状态', riskDelta: 15, isOptimal: false, consequence: '遗漏设备与应急确认', branch: 'continue' },
        { id: 'c', label: '应急消防设施', riskDelta: 10, isOptimal: false, consequence: '遗漏测试对象确认', branch: 'continue' },
        { id: 'd', label: '全部确认（设备+电池+消防+人员资质）', riskDelta: -10, isOptimal: true, consequence: '测试前风险可控', branch: 'continue' },
      ],
    },
    {
      id: 'd2', phase: 'anomaly', nodeKey: 'n2',
      title: '决策点② · 异常温升处置',
      question: '发现 1# 电池包温度异常升至 65℃ 后，应如何处置？',
      regulationRef: 'GB/T 42288-2022 电化学储能电站安全规程',
      timeLimitSec: 60,
      options: [
        { id: 'a', label: '继续测试观察', riskDelta: 35, isOptimal: false, consequence: '热失控持续发展，风险 40%→65%', branch: 'continue' },
        { id: 'b', label: '立即停止测试并隔离设备', riskDelta: -30, isOptimal: true, consequence: '切断能量输入，事故得到控制', branch: 'early_success' },
        { id: 'c', label: '上报负责人等待指令', riskDelta: 20, isOptimal: false, consequence: '响应延迟，风险持续攀升', branch: 'continue' },
        { id: 'd', label: '忽略告警继续作业', riskDelta: 50, isOptimal: false, consequence: '直接进入严重事故路径', branch: 'catastrophe' },
      ],
    },
    {
      id: 'd3', phase: 'flashover', nodeKey: 'n4',
      title: '决策点③ · 闪爆后处置优先级',
      question: '闪爆发生后，最优先采取哪项措施？',
      regulationRef: 'DL/T 2528-2022 应急预案编制导则',
      timeLimitSec: 45,
      options: [
        { id: 'a', label: '继续测试记录数据', riskDelta: 40, isOptimal: false, consequence: '危及人员生命安全', branch: 'continue' },
        { id: 'b', label: '立即组织人员撤离并报警', riskDelta: -20, isOptimal: true, consequence: '符合「生命第一」原则', branch: 'continue' },
        { id: 'c', label: '打开设备检查', riskDelta: 35, isOptimal: false, consequence: '二次爆炸与中毒风险', branch: 'continue' },
        { id: 'd', label: '等待事故自行结束', riskDelta: 30, isOptimal: false, consequence: '延误救援黄金窗口', branch: 'continue' },
      ],
    },
  ],
  evidence: [
    { id: 'e1', phase: 'testing', title: '测试区监控截图', type: 'video', summary: '14:10 测试启动画面，人员站位正常', unlocked: false },
    { id: 'e2', phase: 'anomaly', title: 'BMS 告警日志', type: 'bms', summary: '14:24 温度一级告警，单体压差超限', unlocked: false },
    { id: 'e3', phase: 'anomaly', title: '温度记录曲线', type: 'thermal', summary: '15 分钟内温升 37℃', unlocked: false },
    { id: 'e4', phase: 'thermal_runaway', title: '热成像图', type: 'thermal', summary: '模组热点集中于 1# 包中部', unlocked: false },
    { id: 'e5', phase: 'thermal_runaway', title: '气体监测记录', type: 'gas', summary: 'H₂/VOC 浓度超阈值', unlocked: false },
    { id: 'e6', phase: 'flashover', title: '操作记录票证', type: 'ops', summary: '异常后未执行停机隔离签字', unlocked: false },
  ],
  fishbone: {
    人员: ['测试人员无证上岗', '异常处置培训不足'],
    设备: ['BMS 预警阈值偏高', '气体监测联锁缺失'],
    方法: ['测试 SOP 未覆盖温升中止条件', '应急预案未演练'],
    环境: ['测试区通风不足', '高温季节散热负荷大'],
    管理: ['测试审批流于形式', '监护责任未落实'],
  },
  fiveWhy: [
    '为什么发生闪爆？——可燃气体达到爆炸极限引发爆燃。',
    '为什么气体积聚？——热失控持续未得到有效遏制。',
    '为什么热失控发展？——异常温升后未立即停机隔离。',
    '为什么未停机？——继续测试观察，忽视 BMS 一级告警。',
    '为什么忽视告警？——测试前安全确认不完整，风险意识薄弱。',
  ],
  fta: [
    { label: '闪爆事故', children: ['热失控', '异常未处置'] },
    { label: '热失控', children: ['内部短路', '散热失效'] },
    { label: '异常未处置', children: ['继续测试', '预警失效'] },
  ],
  courseLinks: [
    { title: '储能测试作业安全规范', reason: '强化测试前三查与人员资质' },
    { title: '锂电池热失控机理', reason: '理解温升-气体-爆燃链' },
    { title: 'BMS 安全管理', reason: '告警分级与联锁停机' },
    { title: '储能消防与应急处置', reason: '闪爆后人员撤离与警戒' },
  ],
  mentorFaqs: [
    { q: '为什么温度会突然升高？', a: '可能由电芯内短路、过充或散热不良引发自发热，温度与气体浓度联动上升是热失控前兆。', ref: 'GB/T 42288' },
    { q: '现在应该怎么办？', a: '立即停止测试、切断直流回路、启动通风与气体监测，人员撤离至安全区后上报。', ref: '测试安全规范' },
    { q: '事故是否可以避免？', a: '若在 65℃ 告警时立即停机隔离，大概率可避免闪爆。关键在「预警即行动」。' },
    { q: '规范要求是什么？', a: '测试作业须持证上岗，异常告警必须响应，严禁在不明温升情况下继续充放电。', ref: 'DL/T 2528' },
  ],
}
