import type { TimelineScenario } from '../types'

/** 北京丰台储能电站 4·16 火灾爆炸 — 时间轴推演剧本 */
export const beijing416Scenario: TimelineScenario = {
  id: 'td-beijing-416',
  code: 'beijing_416',
  title: '北京丰台 4·16 储能电站事故推演',
  subtitle: '从异常预警到热失控扩散的沉浸式决策训练',
  caseRef: '003',
  location: '北京市丰台区某储能电站',
  accidentDate: '2021-04-16',
  durationMinutes: 45,
  nodes: [
    {
      key: 'n0',
      phase: 'normal',
      title: 'T0 正常运行',
      narrative: '储能系统处于并网运行状态，BMS 显示各簇 SOC、温度正常。值班员正在进行例行巡检。',
      offsetMin: 0,
      scene: { containerHeat: [0.1, 0.1, 0.1, 0.1], smokeLevel: 0, fireLevel: 0, explosionFlash: 0, alarmActive: false, ventilationOn: true, isolationDone: false },
      telemetry: { t: 0, temp: 28, voltage: 3.32, soc: 72, h2: 0, smoke: 0 },
    },
    {
      key: 'n1',
      phase: 'warning',
      title: 'T+5min 异常预警',
      narrative: '2# 储能舱温度缓慢上升，BMS 发出一级预警。气体探测器读数轻微波动，现场无明显异味。',
      offsetMin: 5,
      scene: { containerHeat: [0.15, 0.55, 0.12, 0.1], smokeLevel: 0.05, fireLevel: 0, explosionFlash: 0, alarmActive: true, ventilationOn: true, isolationDone: false },
      telemetry: { t: 5, temp: 42, voltage: 3.28, soc: 71, h2: 15, smoke: 0.08 },
    },
    {
      key: 'n2',
      phase: 'thermal_runaway',
      title: 'T+15min 热失控萌芽',
      narrative: '2# 舱内温度骤升，单体电压离散度增大，疑似电芯内部短路引发自发热。舱门接缝处可见轻微白雾。',
      offsetMin: 15,
      scene: { containerHeat: [0.2, 0.85, 0.25, 0.15], smokeLevel: 0.35, fireLevel: 0.15, explosionFlash: 0, alarmActive: true, ventilationOn: true, isolationDone: false },
      telemetry: { t: 15, temp: 78, voltage: 3.12, soc: 68, h2: 120, smoke: 0.35 },
    },
    {
      key: 'n3',
      phase: 'spread',
      title: 'T+25min 火势扩散',
      narrative: '热失控向相邻电池簇蔓延，舱内烟雾浓度升高。若不及时切断直流回路并启动应急通风，事故将快速升级。',
      offsetMin: 25,
      scene: { containerHeat: [0.4, 1, 0.7, 0.35], smokeLevel: 0.72, fireLevel: 0.55, explosionFlash: 0, alarmActive: true, ventilationOn: false, isolationDone: false },
      telemetry: { t: 25, temp: 145, voltage: 2.85, soc: 62, h2: 680, smoke: 0.72 },
    },
    {
      key: 'n4',
      phase: 'explosion',
      title: 'T+35min 爆炸冲击',
      narrative: '可燃气体积聚达到爆炸下限，舱内发生爆燃。冲击波损毁相邻设备，现场进入全面应急响应。',
      offsetMin: 35,
      scene: { containerHeat: [0.9, 1, 1, 0.8], smokeLevel: 1, fireLevel: 1, explosionFlash: 1, alarmActive: true, ventilationOn: false, isolationDone: false },
      telemetry: { t: 35, temp: 420, voltage: 0, soc: 0, h2: 0, smoke: 1 },
    },
    {
      key: 'n5',
      phase: 'debrief',
      title: '事故复盘',
      narrative: '推演结束。请结合决策路径分析根因、法规依据与改进措施。',
      offsetMin: 45,
      scene: { containerHeat: [0.5, 0.5, 0.5, 0.5], smokeLevel: 0.3, fireLevel: 0.2, explosionFlash: 0, alarmActive: false, ventilationOn: false, isolationDone: true },
      telemetry: { t: 45, temp: 35, voltage: 0, soc: 0, h2: 0, smoke: 0.1 },
    },
  ],
  decisions: [
    {
      id: 'd1',
      nodeKey: 'n1',
      offsetMin: 5,
      phase: 'warning',
      question: '【T0 决策】BMS 一级预警触发，你作为值班负责人首先应采取？',
      regulationRef: 'GB/T 42288-2022 电化学储能电站安全规程',
      timeLimitSec: 90,
      options: [
        { id: 'a', label: '立即远程切断 2# 舱直流回路并派员现场确认', consequence: '切断能量输入，为后续处置争取窗口', riskDelta: -15, branchHint: 'optimal', isOptimal: true },
        { id: 'b', label: '继续观察 15 分钟，等待温度自行回落', consequence: '延误处置，热失控风险持续累积', riskDelta: 25, branchHint: 'delayed', isOptimal: false },
        { id: 'c', label: '仅通知站长，不做现场操作', consequence: '响应链断裂，错过黄金处置期', riskDelta: 35, branchHint: 'escalated', isOptimal: false },
      ],
    },
    {
      id: 'd2',
      nodeKey: 'n2',
      offsetMin: 15,
      phase: 'thermal_runaway',
      question: '【T+15 决策】现场确认舱内温度持续上升、出现白雾，下一步？',
      regulationRef: 'DL/T 2528-2022 电化学储能电站应急预案编制导则',
      timeLimitSec: 60,
      options: [
        { id: 'a', label: '启动应急通风 + 气体消防 + 人员撤离至安全区', consequence: '控制可燃气体浓度，保障人员安全', riskDelta: -20, branchHint: 'optimal', isOptimal: true },
        { id: 'b', label: '打开舱门直接查看电池状态', consequence: '氧气涌入加剧热失控，危及人身安全', riskDelta: 40, branchHint: 'catastrophic', isOptimal: false },
        { id: 'c', label: '仅使用手持灭火器对准冒烟点喷射', consequence: '未切断电源，处置手段与事故阶段不匹配', riskDelta: 20, branchHint: 'escalated', isOptimal: false },
      ],
    },
    {
      id: 'd3',
      nodeKey: 'n3',
      offsetMin: 25,
      phase: 'spread',
      question: '【T+25 决策】火势向相邻簇蔓延，现场指挥应？',
      regulationRef: 'GB 50016 建筑设计防火规范（储能部分）',
      timeLimitSec: 45,
      options: [
        { id: 'a', label: '全面断电隔离 + 边界冷却 + 上报启动公司级应急预案', consequence: '阻断蔓延路径，符合分级响应要求', riskDelta: -25, branchHint: 'optimal', isOptimal: true },
        { id: 'b', label: '集中水枪冷却 2# 舱外壳，人员近距离作业', consequence: '水与高压直流接触风险，人员伤亡隐患', riskDelta: 30, branchHint: 'escalated', isOptimal: false },
        { id: 'c', label: '等待消防队到场，现场不作处置', consequence: '错过遏制窗口，爆炸概率大幅上升', riskDelta: 45, branchHint: 'catastrophic', isOptimal: false },
      ],
    },
  ],
  courseLinks: [
    { title: '储能电站 BMS 预警处置', reason: '强化预警分级响应与远程切断流程' },
    { title: '热失控机理与早期识别', reason: '理解温度-电压-气体三联征象' },
    { title: '储能消防与应急通风', reason: '掌握气体消防与通风联锁操作' },
    { title: '事故调查与根因分析', reason: '5Why + 鱼骨图复盘方法' },
  ],
  fishbone: {
    人员: ['值班员对预警响应迟缓', '现场指挥权限不清晰'],
    设备: ['BMS 预警阈值设置偏高', '气体消防系统未联锁启动'],
    方法: ['缺乏分级处置 SOP', '未演练热失控专项预案'],
    环境: ['舱内通风不足', '高温季节散热负荷大'],
    管理: ['双重确认机制缺失', '运维交接信息不完整'],
  },
  fiveWhy: [
    '为什么发生爆炸？——舱内可燃气体达到爆炸极限。',
    '为什么气体积聚？——热失控持续未得到有效遏制。',
    '为什么热失控蔓延？——未及时切断直流回路并启动应急通风。',
    '为什么未及时切断？——对 BMS 一级预警重视不足，采取观望策略。',
    '为什么重视不足？——培训不到位，未建立预警即行动的肌肉记忆。',
  ],
}
